"""Build and check the knowledge bundle in docs/, an Open Knowledge Format (OKF) v0.2 bundle.

Usage:
    uv run python scripts/build_knowledge.py          # regenerate tables/, the validation SQL and every index.md
    uv run python scripts/build_knowledge.py --check  # conformance, links, staleness and generated-file drift

Generated here, never edited by hand:
  * docs/tables/**: one concept per dbt model, seed and source, from dbt/target/manifest.json and catalog.json.
    Run after `dbt docs generate` (scripts/run_pipeline.py does both). Edit descriptions in dbt/**/_*.yml.
  * powerbi/validation_queries.sql: the SQL of the Attested Computations in docs/computations/.
  * index.md files: entry titles and descriptions come from each concept's frontmatter. Outside docs/tables/
    the order and section headings are curated by hand and kept; new concepts are appended to the last
    section and deleted ones dropped.
Conventions for the bundle are in docs/conventions.md.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
BUNDLE = ROOT / "docs"
TABLES = BUNDLE / "tables"
COMPUTATIONS = BUNDLE / "computations"
SOURCES = BUNDLE / "sources"
TARGET = ROOT / "dbt" / "target"
VALIDATION_SQL = ROOT / "powerbi" / "validation_queries.sql"
ACTOR = "build_knowledge/1"
OKF_VERSION = "0.2"
RESERVED = {"index.md", "log.md"}
LAYERS = ["raw", "reference", "staging", "intermediate", "analytics"]
FOLDER_ORDER = ["core", "performance", "recurrence"]  # sections of the analytics index

# Heading of each directory's index, and its entry in the parent index.
DIRS = {
    "": ("Memphis 311 Service Reliability", ""),
    "decisions": ("Decisions", "Every judgment call, with its evidence, the alternatives and what it affects (D01–D32)."),
    "methodology": ("Methodology", "How each measure is defined and why: populations, responsiveness, backlog, recurrence, persistence, geography, limitations."),
    "metrics": ("Metrics", "Dashboard measures: definition, DAX measure names, source columns, sanctioned computation and last checked value."),
    "computations": ("Computations", "Attested Computations: the sanctioned BigQuery SQL behind every headline figure."),
    "findings": ("Findings", "What the data shows, with figures from the analytics marts."),
    "tables": ("Tables", "Generated from dbt: one concept per BigQuery table, view, seed and raw source, with schema, lineage and tests."),
    "tables/raw": ("raw dataset", "Append-only extraction batches and the ingestion audit table."),
    "tables/reference": ("reference dataset", "Hand-reviewed seed data."),
    "tables/staging": ("staging dataset", "Latest version of each source record, standardized."),
    "tables/intermediate": ("intermediate dataset", "Location entities, recurrence originals and candidate pairs, daily open backlog."),
    "tables/analytics": ("analytics dataset", "Facts, dimensions and aggregate marts read by Power BI."),
    "sources": ("Sources", "External data the pipeline reads."),
    "playbooks": ("Playbooks", "How to run, refresh, extend and validate the project."),
    "dashboard": ("Dashboard", "The Power BI report, page by page."),
    "project": ("Project", "The plan the project was built from, and ready-to-use portfolio text."),
    "references": ("References", "Executor and attester code for the Attested Computations."),
}
SQL_HEADER = [
    "-- Expected values for the Power BI measures (Week 7 task 7: check dashboard calculations against SQL output).",
    "-- Each query mirrors one DAX measure in measures.dax with no slicers applied (all dates, all categories).",
    "-- Run in the BigQuery console (project mem-311) and compare with the cards described in build_guide.md.",
    "-- Generated by scripts/build_knowledge.py from the Attested Computations in docs/computations/; edit those.",
]

FRONTMATTER = re.compile(r"\A---\r?\n(.*?)\r?\n---[ \t]*(?:\r?\n|\Z)", re.S)
ENTRY = re.compile(r"^\*\s+\[[^\]]*\]\(([^)\s]+)\)")
LINK = re.compile(r"\[[^\]]*\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
DECISION_REF = re.compile(r"(?<![\w\[/-])D(?:0[1-9]|[1-9]\d)(?![\w-])")
ACTOR_ID = re.compile(r"^(?:human|process):\S+$|^[\w.-]+/[\w.-]+$")
URI_SCHEME = re.compile(r"^[a-z][a-z0-9+.-]*:", re.I)


def parse(text: str) -> tuple[dict | None, str]:
    """(frontmatter, body). Raises yaml.YAMLError on malformed frontmatter."""
    m = FRONTMATTER.match(text)
    if not m:
        return None, text
    meta = yaml.safe_load(m.group(1))
    return (meta if isinstance(meta, dict) else None), text[m.end():]


def q(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def iso(ts: str) -> str:
    return dt.datetime.fromisoformat(ts).astimezone(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def current(path: Path, plan: dict[Path, str | None]) -> str | None:
    if path in plan:
        return plan[path]
    return path.read_text(encoding="utf-8") if path.exists() else None


def concept_meta(path: Path, plan: dict[Path, str | None]) -> dict:
    text = current(path, plan)
    return (parse(text)[0] or {}) if text else {}


def first_sentence(text: str) -> str:
    m = re.match(r"(.+?[.!?])(?:\s|$)", text, re.S)
    return " ".join((m.group(1) if m else text).split())


def computation_sql(meta: dict, body: str, path: Path) -> str | None:
    """The computation of an Attested Computation: the file named by `computation`, else the first fence
    under `# Computation`."""
    if meta.get("computation"):
        file = path.parent / meta["computation"]
        return file.read_text(encoding="utf-8").strip() if file.exists() else None
    m = re.search(r"(?ms)^# Computation[ \t]*$.*?^```[\w-]*\n(.*?)^```", body)
    return m.group(1).strip() if m else None


# ---------------------------------------------------------------------------------------------- tables


def decision_files() -> dict[str, str]:
    return {p.name[:3]: p.name for p in (BUNDLE / "decisions").glob("D[0-9][0-9]-*.md")}


def link_decisions(text: str, to_decisions: str, files: dict[str, str]) -> str:
    return DECISION_REF.sub(lambda m: f"[{m[0]}]({to_decisions}{files[m[0]]})" if m[0] in files else m[0], text)


def external_concepts() -> dict[str, str]:
    """BigQuery table id -> concept path (relative to the bundle) for the concepts in docs/sources/."""
    found = {}
    for p in SOURCES.glob("*.md"):
        if p.name not in RESERVED and (table_id := (parse(p.read_text(encoding="utf-8"))[0] or {}).get("table_id")):
            found[table_id] = f"sources/{p.name}"
    return found


def describe_test(test: dict, link_to: dict[str, str]) -> str:
    meta = test["test_metadata"]
    kwargs = meta["kwargs"]
    column = kwargs.get("column_name")
    text = f"`{meta['name']}` on " + (f"`{column}`" if column else "the table")
    if meta["name"] == "relationships":
        ref = re.sub(r"^ref\('([^']+)'\)$", r"\1", kwargs["to"])
        text += f" → {link_to.get(ref, f'`{ref}`')}.`{kwargs['field']}`"
    elif meta["name"] == "accepted_values":
        text += ": " + ", ".join(f"`{v}`" for v in kwargs["values"])
    elif meta["name"] == "accepted_range":
        text += f": {kwargs.get('min_value', '…')} to {kwargs.get('max_value', '…')}"
    elif meta["name"] == "unique_combination_of_columns":
        text = f"`{meta['name']}` on " + ", ".join(f"`{c}`" for c in kwargs["combination_of_columns"])
    if str(test["config"].get("severity", "")).lower() == "warn":
        text += " (warn)"
    return text


def keep_stamp(path: Path, new: str) -> str:
    """Keep the existing file, and so its generated.at, when nothing but the stamp would change."""
    if path.exists():
        old = path.read_text(encoding="utf-8")
        unstamped = re.compile(r"(?m)^generated: .*$")
        if unstamped.sub("", old) == unstamped.sub("", new):
            return old
    return new


def table_concepts() -> dict[Path, str | None]:
    """docs/tables/<dataset>/<name>.md for every dbt model, seed and source, plus their index files.
    Empty when dbt has not written manifest.json and catalog.json. None marks a file to delete."""
    if not (TARGET / "manifest.json").exists() or not (TARGET / "catalog.json").exists():
        return {}
    manifest = json.loads((TARGET / "manifest.json").read_text(encoding="utf-8"))
    catalog = json.loads((TARGET / "catalog.json").read_text(encoding="utf-8"))
    stamp = iso(catalog["metadata"]["generated_at"])
    decisions = decision_files()
    externals = external_concepts()
    nodes = {uid: n for uid, n in {**manifest["nodes"], **manifest["sources"]}.items()
             if n["resource_type"] in ("model", "seed", "source")}
    by_name = {n["name"]: uid for uid, n in nodes.items() if n["resource_type"] != "source"}

    def link(uid: str, from_schema: str = "") -> str:
        n = nodes[uid]
        target = f"{n['name']}.md" if n["schema"] == from_schema else f"../{n['schema']}/{n['name']}.md"
        return f"[{n['name']}]({target})"

    used_by: dict[str, list[str]] = {uid: [] for uid in nodes}
    for uid, n in nodes.items():
        for dep in n.get("depends_on", {}).get("nodes", []):
            if dep in used_by:
                used_by[dep].append(uid)
    tests: dict[str, list[str]] = {uid: [] for uid in nodes}
    for t in manifest["nodes"].values():
        if t["resource_type"] != "test":
            continue
        deps = t["depends_on"]["nodes"]
        if t.get("test_metadata"):
            owner = t.get("attached_node") or (deps[0] if len(deps) == 1 else None)
            if owner in tests:
                link_to = {name: link(u, nodes[owner]["schema"]) for name, u in by_name.items()}
                tests[owner].append(describe_test(t, link_to))
        else:
            path = "dbt/" + t["original_file_path"].replace("\\", "/")
            for dep in deps:
                if dep in tests:
                    tests[dep].append(f"[`{t['name']}`](../../../{path})")

    def order(uid: str) -> tuple[int, str]:
        return LAYERS.index(nodes[uid]["schema"]) if nodes[uid]["schema"] in LAYERS else 99, nodes[uid]["name"]

    plan: dict[Path, str | None] = {}
    groups: dict[str, dict[str, list[str]]] = {}
    for uid, n in sorted(nodes.items(), key=lambda kv: order(kv[0])):
        kind, schema, name = n["resource_type"], n["schema"], n["name"]
        file = "dbt/" + n["original_file_path"].replace("\\", "/")
        folder = {"source": "source", "seed": "seed"}.get(kind) or file.split("/")[-2]
        if folder == "marts":
            folder = schema
        materialized = n["config"].get("materialized", "table") if kind != "source" else "table"
        cat = catalog["sources" if kind == "source" else "nodes"].get(uid, {})
        rows = cat.get("stats", {}).get("num_rows", {}).get("value")
        description = " ".join((n.get("description") or "").split())
        if kind == "source" and n.get("source_description"):
            description = f"{description} {' '.join(n['source_description'].split())}".strip()

        sources = [("dbt-source" if kind == "source" else f"dbt-{kind}", file,
                    {"model": "dbt model SQL", "seed": "Seed CSV", "source": "dbt source definition"}[kind])]
        if kind != "source" and n.get("patch_path"):
            sources.append(("dbt-schema", "dbt/" + n["patch_path"].split("://", 1)[-1].replace("\\", "/"),
                            "dbt descriptions and tests"))
        if kind == "source":
            sources.append(("extractor", "ingestion/extract_311.py", "Extractor that writes the table"))
        fm = [
            "---",
            f"type: {'BigQuery View' if materialized == 'view' else 'BigQuery Table'}",
            f"title: {name}",
            f"description: {q(first_sentence(description))}",
            f"resource: https://console.cloud.google.com/bigquery?p={n['database']}&d={schema}&t={name}",
            f"tags: [{', '.join(dict.fromkeys([schema, folder]))}]",
            f"generated: {{ by: {ACTOR}, at: {stamp} }}",
            "sources:",
        ]
        for sid, path, title in sources:
            fm += [f"  - id: {sid}", f"    resource: ../../../{path}", f"    title: {title}"]
        fm += [f"table_id: {n['database']}.{schema}.{name}", f"materialized: {materialized}"]
        if rows not in (None, ""):
            fm.append(f"row_count: {int(rows)}")
        fm.append("---")

        body = ["", link_decisions(description, "../../decisions/", decisions), "", "# Schema", "",
                "| Column | Type | Description |", "|---|---|---|"]
        documented = n.get("columns", {})
        columns = sorted(cat["columns"].values(), key=lambda c: c["index"]) if cat.get("columns") \
            else list(documented.values())
        for c in columns:
            doc = (documented.get(c["name"]) or documented.get(c["name"].lower()) or {}).get("description") or ""
            doc = link_decisions(" ".join(doc.replace("|", "/").split()), "../../decisions/", decisions)
            body.append(f"| `{c['name']}` | {c.get('type') or c.get('data_type') or ''} | {doc} |")

        built_from = [link(d, schema) for d in sorted((d for d in n.get("depends_on", {}).get("nodes", [])
                                                       if d in nodes), key=order)]
        for table_id in sorted(set(re.findall(r"bigquery-public-data\.\w+\.\w+", n.get("raw_code") or ""))):
            concept = externals.get(table_id)
            built_from.append(f"`{table_id}`" + (f" ([source](../../{concept}))" if concept else ""))
        if kind == "source":
            built_from.append("[`ingestion/extract_311.py`](../../../ingestion/extract_311.py), which reads the "
                              "[Memphis 311 FeatureServer](../../sources/memphis-311-featureserver.md)")
        body += ["", "# Lineage", ""]
        if built_from:
            body += ["Built from:", ""] + [f"* {b}" for b in built_from] + [""]
        consumers = [link(u, schema) for u in sorted(used_by[uid], key=order)]
        body += (["Used by:", ""] + [f"* {c}" for c in consumers]) if consumers else ["Not used by another model."]
        if tests[uid]:  # manifest order varies between dbt runs; singular tests last
            body += ["", "# Tests", ""] + [f"* {t}" for t in sorted(tests[uid], key=lambda t: (t.startswith("["), t))]

        path = TABLES / schema / f"{name}.md"
        plan[path] = keep_stamp(path, "\n".join(fm + body) + "\n")
        groups.setdefault(schema, {}).setdefault(folder, []).append(
            f"* [{name}]({name}.md) - {first_sentence(description)}")

    for existing in TABLES.rglob("*.md"):
        if existing.name not in RESERVED and existing not in plan:
            plan[existing] = None
    for schema, folders in groups.items():
        title = DIRS.get(f"tables/{schema}", (schema, ""))[0]
        lines = []
        for folder, entries in sorted(folders.items(), key=lambda kv: (kv[0] not in FOLDER_ORDER,
                                                                       FOLDER_ORDER.index(kv[0]) if kv[0] in FOLDER_ORDER else 0, kv[0])):
            heading = title if len(folders) == 1 else folder.capitalize()
            lines += [f"# {heading}", "", *entries, ""]
        plan[TABLES / schema / "index.md"] = "\n".join(lines).rstrip() + "\n"
    lines = [f"# {DIRS['tables'][0]}", ""]
    for schema in sorted(groups, key=lambda s: LAYERS.index(s) if s in LAYERS else 99):
        title, desc = DIRS.get(f"tables/{schema}", (schema, ""))
        lines.append(f"* [{title}]({schema}/index.md) - {desc}".rstrip(" -"))
    plan[TABLES / "index.md"] = "\n".join(lines) + "\n"
    return plan


# ---------------------------------------------------------------------------------------------- indexes


def index_targets(directory: Path, plan: dict[Path, str | None]) -> list[str]:
    text = current(directory / "index.md", plan)
    return [m.group(1) for line in (text or "").splitlines() if (m := ENTRY.match(line))]


def entry(title: str, target: str, description: str | None, status: str | None = None) -> str:
    flag = f" *({status})*" if status in ("draft", "deprecated") else ""
    return f"* [{title}]({target}){flag}" + (f" - {' '.join(str(description).split())}" if description else "")


def has_concepts(directory: Path, plan: dict[Path, str | None]) -> bool:
    in_plan = any(p.parent == directory or directory in p.parents for p, t in plan.items() if t is not None
                  and p.suffix == ".md")
    return in_plan or any(p.name not in RESERVED for p in directory.rglob("*.md"))


def index_files(plan: dict[Path, str | None]) -> dict[Path, str]:
    """Every index.md outside docs/tables/, deepest directories first so parents see their children."""
    out: dict[Path, str] = {}
    directories = [BUNDLE] + [d for d in BUNDLE.rglob("*") if d.is_dir()]
    for directory in sorted(directories, key=lambda d: -len(d.parts)):
        if directory == TABLES or TABLES in directory.parents or not has_concepts(directory, plan):
            continue
        rel = directory.relative_to(BUNDLE).as_posix().strip(".")
        entries: dict[str, str] = {}
        for p in sorted(directory.glob("*.md")):
            if p.name not in RESERVED:
                meta = concept_meta(p, plan)
                entries[p.name] = entry(meta.get("title") or p.stem, p.name, meta.get("description"),
                                        meta.get("status"))
        children = {d for d in directory.iterdir() if d.is_dir()}
        children |= {directory / p.relative_to(directory).parts[0] for p in plan  # dirs not written yet
                     if directory in p.parents and len(p.relative_to(directory).parts) > 1}
        for child in sorted(children):
            if has_concepts(child, {**plan, **out}):
                title, desc = DIRS.get(child.relative_to(BUNDLE).as_posix(), (child.name, ""))
                entries[f"{child.name}/index.md"] = entry(title, f"{child.name}/index.md", desc)
        heading = DIRS.get(rel, (directory.name, ""))[0]
        old = current(directory / "index.md", plan)
        if old is None:
            lines = [f"# {heading}", "", *entries.values()]
        else:
            lines, used = [], set()
            for line in (parse(old)[1]).strip("\n").splitlines():
                m = ENTRY.match(line)
                if not m:
                    lines.append(line)
                elif m.group(1) in entries and m.group(1) not in used:
                    lines.append(entries[m.group(1)])
                    used.add(m.group(1))
                elif m.group(1) not in entries and resolves(m.group(1), directory / "index.md"):
                    lines.append(line)  # a curated entry pointing elsewhere in the bundle
            new = [line for target, line in entries.items() if target not in used]
            if new:
                if not any(line.startswith("# ") for line in lines):
                    lines = [f"# {heading}", "", *lines]
                while lines and not lines[-1].strip():
                    lines.pop()
                lines += new
        text = re.sub(r"\n{3,}", "\n\n", "\n".join(lines).strip("\n")) + "\n"
        if directory == BUNDLE:
            text = f'---\nokf_version: "{OKF_VERSION}"\n---\n\n{text}'
        out[directory / "index.md"] = text
    return out


# ---------------------------------------------------------------------------------------------- validation SQL


def validation_sql() -> str:
    curated = [COMPUTATIONS / t for t in index_targets(COMPUTATIONS, {}) if "/" not in t]
    paths = [p for p in curated if p.exists()]
    paths += [p for p in sorted(COMPUTATIONS.glob("*.md")) if p.name not in RESERVED and p not in paths]
    out = list(SQL_HEADER)
    for path in paths:
        meta, body = parse(path.read_text(encoding="utf-8"))
        if not meta or meta.get("type") != "Attested Computation" or meta.get("runtime") != "bigquery":
            continue
        sql = computation_sql(meta, body, path)
        if not sql:
            continue
        out += ["", f"-- {meta.get('title', path.stem)} (docs/computations/{path.name})"]
        if meta.get("dax_measures"):
            out.append("-- DAX: " + ", ".join(f"[{m}]" for m in meta["dax_measures"]))
        out.append(sql.rstrip().rstrip(";") + ";")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------- check


def aware(value) -> bool:
    """An ISO 8601 datetime with an explicit offset, as OKF requires for every timestamp."""
    if isinstance(value, dt.datetime):
        return value.tzinfo is not None
    if isinstance(value, str):
        try:
            return dt.datetime.fromisoformat(value).tzinfo is not None
        except ValueError:
            return False
    return False


def as_utc(value) -> dt.datetime:
    return value if isinstance(value, dt.datetime) else dt.datetime.fromisoformat(value)


def is_path(value) -> bool:
    return isinstance(value, str) and "/" in value and " " not in value and not URI_SCHEME.match(value)


def resolves(target: str, path: Path) -> bool:
    target = target.split("#", 1)[0]
    if not target:
        return True
    return ((BUNDLE / target[1:]) if target.startswith("/") else (path.parent / target)).exists()


def prose(body: str) -> str:
    """The body without fenced blocks and inline code, where links and footnotes are only examples."""
    return re.sub(r"`[^`\n]*`", "", re.sub(r"(?ms)^```.*?^```", "", body))


def links(body: str) -> list[str]:
    return [t for t in LINK.findall(prose(body)) if not URI_SCHEME.match(t) and not t.startswith("#")]


def check_concept(meta: dict, body: str, path: Path) -> list[str]:
    errors = []
    if not str(meta.get("type") or "").strip():
        errors.append("frontmatter has no type")
    generated = meta.get("generated")
    if generated is not None:
        if not isinstance(generated, dict) or not generated.get("by"):
            errors.append("generated needs a `by` actor")
        else:
            if not ACTOR_ID.match(str(generated["by"])):
                errors.append(f"generated.by `{generated['by']}` is not an actor (<tool>/<version>, human:, process:)")
            if "at" in generated and not aware(generated["at"]):
                errors.append("generated.at must be an ISO 8601 datetime with a UTC offset")
    verified = meta.get("verified")
    if verified is not None:
        for v in [verified] if isinstance(verified, dict) else verified if isinstance(verified, list) else [None]:
            if not isinstance(v, dict) or not ACTOR_ID.match(str(v.get("by", ""))) or not aware(v.get("at")):
                errors.append("each verified entry needs an actor `by` and an `at` datetime with offset")
    if meta.get("status", "stable") not in ("draft", "stable", "deprecated"):
        errors.append(f"status `{meta['status']}` is not draft, stable or deprecated")
    if "stale_after" in meta and not aware(meta["stale_after"]):
        errors.append("stale_after must be an ISO 8601 datetime with a UTC offset")
    ids = set()
    for s in meta.get("sources") or []:
        if not isinstance(s, dict) or not s.get("resource"):
            errors.append("every sources entry needs a resource")
            continue
        ids.add(s.get("id"))
        if is_path(s["resource"]) and not resolves(s["resource"], path):
            errors.append(f"sources resource {s['resource']} does not exist")
    for label in sorted(set(re.findall(r"\[\^([^\]]+)\]", prose(body)))):
        if label not in ids:
            errors.append(f"footnote [^{label}] has no sources entry with that id")
    paths = [meta.get("resource"), meta.get("computation")]
    if meta.get("type") == "Attested Computation":
        if not meta.get("runtime"):
            errors.append("an Attested Computation needs a runtime")
        if not computation_sql(meta, body, path):
            errors.append("no computation: add a fenced block under # Computation or a computation path")
        for key in ("executor", "attester"):
            resource = (meta.get(key) or {}).get("resource")
            if not resource:
                errors.append(f"{key}.resource is missing")
            paths.append(resource)
    errors += [f"{p} does not exist" for p in paths if is_path(p) and not resolves(p, path)]
    return errors


def check(plan: dict[Path, str | None]) -> int:
    errors, warnings = [], []
    now = dt.datetime.now(dt.timezone.utc)
    for path in sorted(BUNDLE.rglob("*.md")):
        rel = path.relative_to(BUNDLE).as_posix()
        text = path.read_text(encoding="utf-8")
        try:
            meta, body = parse(text)
        except yaml.YAMLError as e:
            errors.append(f"{rel}: frontmatter is not valid YAML ({getattr(e, 'problem', e)})")
            continue
        if path.name == "index.md":
            if FRONTMATTER.match(text) and (rel != "index.md" or set(meta or {}) != {"okf_version"}):
                errors.append(f"{rel}: only the root index.md may carry frontmatter, and only okf_version")
        elif path.name == "log.md":
            dates = re.findall(r"(?m)^## (.*?)\s*$", body)
            for d in dates:
                if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", d):
                    errors.append(f"{rel}: log heading `{d}` is not an ISO 8601 date (YYYY-MM-DD)")
            if [d for d in dates] != sorted(dates, reverse=True):
                errors.append(f"{rel}: log dates must run newest first")
        elif meta is None:
            errors.append(f"{rel}: no YAML frontmatter")
            continue
        else:
            errors += [f"{rel}: {e}" for e in check_concept(meta, body, path)]
            if meta.get("stale_after") and aware(meta["stale_after"]) and as_utc(meta["stale_after"]) <= now:
                warnings.append(f"{rel}: stale since {meta['stale_after']}; re-check its figures")
        errors += [f"{rel}: broken link {t}" for t in links(body) if not resolves(t, path)]
    for path, content in plan.items():
        on_disk = path.read_text(encoding="utf-8") if path.exists() else None
        if on_disk != content:
            message = f"{path.relative_to(ROOT).as_posix()}: out of date; run scripts/build_knowledge.py"
            (warnings if TABLES in path.parents else errors).append(message)
    for w in warnings:
        print(f"warning: {w}")
    for e in errors:
        print(f"error: {e}")
    concepts = sum(1 for p in BUNDLE.rglob("*.md") if p.name not in RESERVED)
    print(f"{concepts} concepts, {len(errors)} errors, {len(warnings)} warnings")
    return 1 if errors else 0


# ---------------------------------------------------------------------------------------------- main


def build_plan() -> dict[Path, str | None]:
    plan = table_concepts()
    plan[VALIDATION_SQL] = validation_sql()
    plan.update(index_files(plan))
    return plan


def write(plan: dict[Path, str | None]) -> None:
    changed = 0
    for path, content in plan.items():
        if content is None:
            if path.exists():
                path.unlink()
                changed += 1
        elif not path.exists() or path.read_text(encoding="utf-8") != content:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            changed += 1
    for directory in sorted((d for d in TABLES.rglob("*") if d.is_dir()), key=lambda d: -len(d.parts)):
        if not any(directory.iterdir()):
            directory.rmdir()
    print(f"knowledge bundle: {changed} of {len(plan)} generated files updated")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="validate the bundle and fail if generated files drift")
    args = ap.parse_args()
    plan = build_plan()
    if args.check:
        return check(plan)
    write(plan)
    return 0


if __name__ == "__main__":
    sys.exit(main())
