"""Generate docs/data_dictionary.md from dbt's manifest.json (descriptions) and catalog.json (types, row counts).

Run after `dbt docs generate` (scripts/run_pipeline.py does both).
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "dbt" / "target"
OUT = ROOT / "docs" / "data_dictionary.md"
LAYERS = [("staging", "Staging"), ("intermediate", "Intermediate"), ("analytics", "Analytics marts (Power BI)")]


def main() -> None:
    manifest = json.loads((TARGET / "manifest.json").read_text(encoding="utf-8"))
    catalog = json.loads((TARGET / "catalog.json").read_text(encoding="utf-8"))
    lines = [
        "# Data Dictionary",
        "",
        "Generated by `scripts/build_data_dictionary.py` from the dbt manifest and BigQuery catalog; edit the",
        "descriptions in `dbt/models/**/_*.yml`, not here. Types are BigQuery types. Raw-layer fields are the",
        "source ArcGIS fields listed in `ingestion/extract_311.py` (`KEEP_FIELDS`) plus ingestion metadata.",
        "",
    ]
    nodes = [n for n in manifest["nodes"].values() if n["resource_type"] in ("model", "seed")]
    for schema, title in [("reference", "Reference (seeds)")] + LAYERS:
        layer = sorted((n for n in nodes if n["schema"] == schema), key=lambda n: n["name"])
        if not layer:
            continue
        lines += [f"## {title} — `{schema}` dataset", ""]
        for n in layer:
            cat = catalog["nodes"].get(n["unique_id"]) or catalog.get("sources", {}).get(n["unique_id"]) or {}
            stats = cat.get("stats", {})
            rows = stats.get("num_rows", {}).get("value")
            rows_txt = f" · {int(rows):,} rows" if rows not in (None, "") else ""
            lines += [f"### `{n['name']}`{rows_txt}", "", (n.get("description") or "").strip(), "",
                      "| Column | Type | Description |", "|---|---|---|"]
            documented = n.get("columns", {})
            cat_cols = cat.get("columns", {})
            order = sorted(cat_cols.values(), key=lambda c: c["index"]) if cat_cols else documented.values()
            for c in order:
                name = c["name"]
                desc = (documented.get(name, {}) or documented.get(name.lower(), {})).get("description", "")
                ctype = c.get("type", "")
                lines.append(f"| `{name}` | {ctype} | {desc.replace('|', '/').strip()} |")
            lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
